# app.yaml
runtime: python310 # Use Python 3.10
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

instance_class: F2 # App Engine instance type (adjust if needed)
automatic_scaling:
  min_instances: 0
  max_instances: 2
  cpu_utilization:
    target_utilization: 0.6

env_variables:
  # Database
  DB_USER: "postgres"
  DB_PASSWORD: "Ahmed123!"
  DB_HOST: "34.171.67.88"
  DB_PORT: "5432"
  DB_NAME: "document_extraction_db"

  # Google Cloud / PubSub
  PROJECT_ID: "267816589183"
  PUBSUB_SUBSCRIPTION_ID: "pdf-processing-topic-sub"

  # Dataset / PDFs
  DATASET_FILE: "client_dataset.csv"
  PDF_FOLDER: "documents"
  OUTPUT_FILE: "matching_results.xlsx"

  # GCS
  GCS_BUCKET_NAME: "personal-injury-document-bucket"
  GCS_CREDENTIALS_JSON: "/path/to/service-account.json" # Optional if using default credentials

# Optional: network settings for private DB access
# vpc_access_connector:
#   name: "projects/YOUR_PROJECT/locations/us-central1/connectors/YOUR_CONNECTOR"
